name: End-to-end tests
on:
  pull_request:
    branches: 
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Start the application in the background
        run: npm start & npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: npx cypress run
